/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_company_TEA */

#ifndef _Included_com_company_TEA
#define _Included_com_company_TEA
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_company_TEA
 * Method:    encryptLongs
 * Signature: ([J[J)[J
 */
JNIEXPORT jlongArray JNICALL Java_com_company_TEA_encryptLongs
  (JNIEnv *, jclass, jlongArray, jlongArray);

/*
 * Class:     com_company_TEA
 * Method:    decryptLongs
 * Signature: ([J[J)[J
 */
JNIEXPORT jlongArray JNICALL Java_com_company_TEA_decryptLongs
  (JNIEnv *, jclass, jlongArray, jlongArray);

#ifdef __cplusplus
}
#endif
#endif
